# This file will not be overwritten if codegen is rerun

[package]
name = "seL4_RxFirewall_RxFirewall"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.28"
sel4 = { git = "https://github.com/seL4/rust-sel4", features = ["single-threaded"], optional = true }
sel4-logging = { git = "https://github.com/seL4/rust-sel4", optional = true }
linux-raw-sys = { version = "0.11.0", default-features = false }
vstd = { version = "=0.0.0-2026-01-11-0057", default-features=false }
verus_builtin = { version = "=0.0.0-2026-01-11-0057" }
verus_builtin_macros = { version = "=0.0.0-2025-12-07-0054" }
data = { path = "../data" }
firewall-core = { path = "../firewall_core" }

[dev-dependencies]
lazy_static = "1.5.0"
once_cell = "1.21.3"
serial_test = "3.2.0"
proptest = "1.8.0"
env_logger = "0.11.8"

[lib]
path = "src/lib.rs"
crate-type = ["staticlib"]

[features]
sel4 = ["dep:sel4", "dep:sel4-logging" ]

[package.metadata.verus]
verify = true

