[package]
name = "mavlink_firewall"
version = "0.1.0"
edition = "2024"

[dependencies]
# vest = { git = "https://github.com/secure-foundations/vest.git" }
mavlink_parser_vest = { path = "../mavlink_parser_vest" }
vest = {workspace = true}

[package.metadata.verus]
verify = true
